// Code generated by "stringer -type FlagName -linecomment -output flag_string.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlagNameReleaseVersion-0]
	_ = x[FlagNameEventName-1]
	_ = x[FlagNameEventState-2]
}

const _FlagName_name = "release-versionevent-nameevent-state"

var _FlagName_index = [...]uint8{0, 15, 25, 36}

func (i FlagName) String() string {
	if i < 0 || i >= FlagName(len(_FlagName_index)-1) {
		return "FlagName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlagName_name[_FlagName_index[i]:_FlagName_index[i+1]]
}
